name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build
        run: ./setup.py sdist
      - name: Release
        uses: pypa/gh-action-pypi-publish@v1.2.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
